description: GCR Bit Distiller

target:
  service: sing
  name: msrresrchvc
  workspace_name: sysintws

environment:
  image: amlt-sing/acpt-2.2.2-py3.10-cuda12.1
  setup:
    - bash tools/prepare_amlt.sh

code:
  local_dir: /home/v-jiafucheng/Projects/BitDistiller/

data:
  local_dir: data
  remote_dir: gcrbitdistillerdata

jobs:
- name: gcrbitdistillergenerateteacherdata
  sku: 80G2-A100
  command:
  - bash tools/generate_teacher_data_amlt.sh
  mpi: False
  process_count_per_node: 0
  submit_args:
    env:
      NCCL_DEBUG: info
- name: gcrbitdistiller
  sku: 80G8-H100
  command:
  - bash tools/run_kd_qat_amlt.sh
  mpi: False
  process_count_per_node: 0
  submit_args:
    env:
      NCCL_DEBUG: info